In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4, 5])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
a = [2,3,4]
np.asanyarray(a)

array([2, 3, 4])

In [9]:
b = np.matrix(l)
b

matrix([[1, 2, 3, 4, 5]])

In [10]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

- Matrix is already a type of array hence remains unchanged on applying np.asanyarray()

In [11]:
a = np.array(l)
c = a

In [12]:
a

array([1, 2, 3, 4, 5])

In [13]:
c

array([1, 2, 3, 4, 5])

In [14]:
c[0] = 100

In [15]:
c

array([100,   2,   3,   4,   5])

In [16]:
a

array([100,   2,   3,   4,   5])

- Here c and a points to the same array i.e shallow copy takes place

In [17]:
d = np.copy(a)

In [18]:
d

array([100,   2,   3,   4,   5])

In [19]:
d[1] = 56

In [20]:
d

array([100,  56,   3,   4,   5])

In [21]:
a

array([100,   2,   3,   4,   5])

- Here deep copy takes place among a and d.

In [22]:
np.fromfunction(lambda i,j: i == j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
np.fromfunction(lambda i,j: i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [24]:
iterable = (i*i for i in range(5))
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [25]:
np.fromstring('1545 555 6452 1 22 35', sep = ' ', dtype = int)

array([1545,  555, 6452,    1,   22,   35])

In [26]:
np.fromstring('3,4,5,6', sep = ',', dtype = int)

array([3, 4, 5, 6])

## Numpy Data Types

In [27]:
l = [1,2,3,4,45,5]
ar = np.array(l)

In [28]:
ar

array([ 1,  2,  3,  4, 45,  5])

In [29]:
np.ndim(ar)    # Tells the dimension of the array.

1

In [30]:
ar2 = np.array([[1,2,3,34,4] , [2,3,4,5,5,]])
ar2

array([[ 1,  2,  3, 34,  4],
       [ 2,  3,  4,  5,  5]])

In [31]:
np.ndim(ar2)

2

In [32]:
ar.size

6

In [33]:
ar2.size

10

In [34]:
ar.shape

(6,)

In [35]:
ar2.shape

(2, 5)

In [36]:
ar3 = np.array([(1.2, 3,5,4,3), (1,2,3,4,3), (11,2,2,3,4)])

In [37]:
ar3

array([[ 1.2,  3. ,  5. ,  4. ,  3. ],
       [ 1. ,  2. ,  3. ,  4. ,  3. ],
       [11. ,  2. ,  2. ,  3. ,  4. ]])

In [38]:
ar2.dtype

dtype('int64')

- Numpy allows us to start a range from a decimal no. of fractional no.

In [39]:
list(np.arange(2.4, 8.8, .2))

[2.4,
 2.6,
 2.8000000000000003,
 3.0000000000000004,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.8000000000000025,
 5.000000000000002,
 5.200000000000003,
 5.400000000000002,
 5.600000000000003,
 5.8000000000000025,
 6.0000000000000036,
 6.200000000000003,
 6.400000000000004,
 6.600000000000003,
 6.800000000000004,
 7.0000000000000036,
 7.200000000000005,
 7.400000000000004,
 7.600000000000005,
 7.800000000000004,
 8.000000000000005,
 8.200000000000005,
 8.400000000000006,
 8.600000000000005]

In [40]:
np.linspace(1,100,10, dtype = int)    # It will produce 10 data between 1 to 100

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [41]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [42]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
np.zeros((4,5,3), dtype = int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [44]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [45]:
on = np.ones((4,3), dtype = int)

In [46]:
on

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
on + 5

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [48]:
on * 4 

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [49]:
np.empty((3,4))

array([[4.67193825e-310, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.06099790e-312, 1.01855798e-312, 1.23075756e-312,
        1.16709769e-312],
       [1.10343781e-312, 9.76118064e-313, 1.18831764e-312,
        1.90979621e-312]])

- Identity matrix

In [50]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### np.logspace()

In [51]:
np.logspace(1,10, 10, dtype = int, base = 2)  # Produces 10 data between 1 to 10 and return its log base 10 by default.

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

#### np.random()

In [52]:
arr = np.random.randn(3,4)   # Does Standard normal distribution

In [53]:
import pandas as pd
pd.DataFrame(arr)

0         1         2         3
0  0.290528 -2.384337 -0.178596 -0.829685
1 -1.309028  0.792889 -1.968691 -0.142543
2  1.461225  0.487133 -0.079217  1.002527

In [54]:
arr2 = np.random.rand(3,4)

In [55]:
pd.DataFrame(arr2)

0         1         2         3
0  0.861438  0.370277  0.923196  0.274287
1  0.898842  0.023212  0.905594  0.265494
2  0.580831  0.452094  0.249985  0.354572

In [56]:
arr3 = np.random.randint(42, 100, (4,5))

In [57]:
pd.DataFrame(arr3)

0   1   2   3   4
0  96  55  89  93  82
1  72  84  46  73  74
2  53  62  47  93  86
3  93  61  86  67  60

#### reshape()

In [58]:
arr3.reshape(2,10)

array([[96, 55, 89, 93, 82, 72, 84, 46, 73, 74],
       [53, 62, 47, 93, 86, 93, 61, 86, 67, 60]])

In [59]:
arr3.reshape(2,-1)

array([[96, 55, 89, 93, 82, 72, 84, 46, 73, 74],
       [53, 62, 47, 93, 86, 93, 61, 86, 67, 60]])

In [60]:
ar3

array([[ 1.2,  3. ,  5. ,  4. ,  3. ],
       [ 1. ,  2. ,  3. ,  4. ,  3. ],
       [11. ,  2. ,  2. ,  3. ,  4. ]])

In [61]:
ar3[1][3]

4.0

In [62]:
ar3[2:5,1]

array([2.])

In [64]:
arr4 = np.random.randint(1,100,(5,5))

In [67]:
arr4[arr4>50]

array([85, 87, 68, 52, 90, 93, 54, 75, 84, 73, 77, 78, 85, 75])

In [69]:
arr4

array([[85, 87, 42,  2, 50],
       [15, 68, 12, 52, 90],
       [47,  3, 93, 54, 75],
       [84, 73, 77, 78, 40],
       [27, 23, 85, 15, 75]])

In [68]:
arr4[2:4,[1,2]]

array([[ 3, 93],
       [73, 77]])

### Mathematical Operations over arrays.

In [76]:
a1 = np.random.randint(1,3,(3,3))
a2 = np.random.randint(1,3,(3,3))

In [77]:
a1

array([[1, 2, 2],
       [2, 1, 1],
       [2, 1, 1]])

In [80]:
a2

array([[1, 2, 1],
       [1, 1, 1],
       [2, 1, 1]])

In [81]:
a1+a2

array([[2, 4, 3],
       [3, 2, 2],
       [4, 2, 2]])

In [82]:
a1-a2

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 0]])

In [83]:
a1/a2

array([[1., 1., 2.],
       [2., 1., 1.],
       [1., 1., 1.]])

In [85]:
a1*a2  # Not a matrix multiplication.

array([[1, 4, 2],
       [2, 1, 1],
       [4, 1, 1]])

In [87]:
a1@a2    # @ used for matrix multiplication.

array([[7, 6, 5],
       [5, 6, 4],
       [5, 6, 4]])

In [88]:
a1/0

/tmp/ipykernel_144/1504525615.py:1: RuntimeWarning: divide by zero encountered in divide
  a1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [89]:
a1+100

array([[101, 102, 102],
       [102, 101, 101],
       [102, 101, 101]])

In [90]:
a1**2

array([[1, 4, 4],
       [4, 1, 1],
       [4, 1, 1]])

### Broadcasting 

In [92]:
a3 = np.zeros([4,4])

In [95]:
a3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
row = np.array([1,2,3,4])

In [94]:
a3 + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [97]:
col = np.array([[1,2,3,4]])

In [98]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [101]:
col.T + a3

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [103]:
a4 = np.random.randint(1,4, (3,4))

In [104]:
np.sqrt(a4)

array([[1.        , 1.        , 1.73205081, 1.41421356],
       [1.41421356, 1.        , 1.73205081, 1.41421356],
       [1.73205081, 1.41421356, 1.41421356, 1.        ]])

In [105]:
np.exp(a4)

array([[ 2.71828183,  2.71828183, 20.08553692,  7.3890561 ],
       [ 7.3890561 ,  2.71828183, 20.08553692,  7.3890561 ],
       [20.08553692,  7.3890561 ,  7.3890561 ,  2.71828183]])

In [106]:
np.log10(a4)

array([[0.        , 0.        , 0.47712125, 0.30103   ],
       [0.30103   , 0.        , 0.47712125, 0.30103   ],
       [0.47712125, 0.30103   , 0.30103   , 0.        ]])

# END