### Array Manipulation

In [1]:
import numpy as np

In [12]:
arr = np.random.randint(1,10,(3,4))

In [13]:
arr

array([[6, 2, 8, 5],
       [1, 1, 7, 6],
       [3, 4, 6, 3]])

In [14]:
arr.reshape(6,2)

array([[6, 2],
       [8, 5],
       [1, 1],
       [7, 6],
       [3, 4],
       [6, 3]])

In [15]:
arr

array([[6, 2, 8, 5],
       [1, 1, 7, 6],
       [3, 4, 6, 3]])

In [16]:
arr.T

array([[6, 1, 3],
       [2, 1, 4],
       [8, 7, 6],
       [5, 6, 3]])

In [18]:
arr.flatten()  # Covert two dimension array to one dimension.

array([6, 2, 8, 5, 1, 1, 7, 6, 3, 4, 6, 3])