### Array Manipulation

In [14]:
import numpy as np

In [15]:
arr = np.random.randint(1,10,(3,4))

In [16]:
arr

array([[7, 1, 6, 9],
       [5, 7, 3, 5],
       [3, 9, 2, 7]])

In [17]:
arr.reshape(6,2)

array([[7, 1],
       [6, 9],
       [5, 7],
       [3, 5],
       [3, 9],
       [2, 7]])

In [18]:
arr

array([[7, 1, 6, 9],
       [5, 7, 3, 5],
       [3, 9, 2, 7]])

In [19]:
arr.T

array([[7, 5, 3],
       [1, 7, 9],
       [6, 3, 2],
       [9, 5, 7]])

In [20]:
arr.flatten()  # Covert two dimension array to one dimension.

array([7, 1, 6, 9, 5, 7, 3, 5, 3, 9, 2, 7])

- expand_dims()

In [21]:
arr1 = np.array([1,2,3,4,5])

In [22]:
arr1.ndim

1

In [ ]:
np.expand_dims(arr1, axis = 1)

In [25]:
np.expand_dims(arr1, axis = 0)

array([[1, 2, 3, 4, 5]])

In [26]:
data = np.array([[1], [2],[3]])

In [27]:
data

array([[1],
       [2],
       [3]])

In [28]:
np.squeeze(data)

array([1, 2, 3])

In [30]:
arr1

array([1, 2, 3, 4, 5])

In [31]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [32]:
np.roll(arr1, shift = 2)  #Shifts the array by 2 position

array([4, 5, 1, 2, 3])

In [34]:
np.diag(arr1)   # Fills 1D array in the diagonals.

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### Binary Operators

In [35]:
arr1 = np.random.randint(1,10,(3,4))

In [38]:
arr2 = np.random.randint(1,10,(3,4))

In [39]:
arr1

array([[3, 3, 6, 9],
       [7, 1, 7, 8],
       [6, 8, 4, 8]])

In [40]:
arr2

array([[4, 4, 8, 2],
       [4, 1, 1, 7],
       [2, 9, 8, 8]])

In [41]:
arr1 + arr2

array([[ 7,  7, 14, 11],
       [11,  2,  8, 15],
       [ 8, 17, 12, 16]])

In [42]:
arr1 * arr2

array([[12, 12, 48, 18],
       [28,  1,  7, 56],
       [12, 72, 32, 64]])

In [43]:
arr1 / arr2

array([[0.75      , 0.75      , 0.75      , 4.5       ],
       [1.75      , 1.        , 7.        , 1.14285714],
       [3.        , 0.88888889, 0.5       , 1.        ]])

In [44]:
arr1 -arr2

array([[-1, -1, -2,  7],
       [ 3,  0,  6,  1],
       [ 4, -1, -4,  0]])

In [48]:
arr1 % arr2

array([[3, 3, 6, 1],
       [3, 0, 0, 1],
       [0, 8, 4, 0]])

In [49]:
arr1 ** arr2

array([[       81,        81,   1679616,        81],
       [     2401,         1,         7,   2097152],
       [       36, 134217728,     65536,  16777216]])

In [50]:
arr1 & arr2

array([[0, 0, 0, 0],
       [4, 1, 1, 0],
       [2, 8, 0, 8]])

In [51]:
~arr1

array([[ -4,  -4,  -7, -10],
       [ -8,  -2,  -8,  -9],
       [ -7,  -9,  -5,  -9]])

In [53]:
arr1 ^ arr2

array([[ 7,  7, 14, 11],
       [ 3,  0,  6, 15],
       [ 4,  1, 12,  0]])

In [54]:
arr1|arr2

array([[ 7,  7, 14, 11],
       [ 7,  1,  7, 15],
       [ 6,  9, 12,  8]])

In [55]:
arr1>arr2

array([[False, False, False,  True],
       [ True, False,  True,  True],
       [ True, False, False, False]])

### String Function

In [58]:
data1 = np.array(['prateek', 'kumar'])

In [60]:
np.char.upper(data1)

array(['PRATEEK', 'KUMAR'], dtype='<U7')

In [61]:
np.char.title(data1)

array(['Prateek', 'Kumar'], dtype='<U7')

In [62]:
np.char.capitalize(data1)

array(['Prateek', 'Kumar'], dtype='<U7')

### Mathematical Functions.

In [63]:
arr1

array([[3, 3, 6, 9],
       [7, 1, 7, 8],
       [6, 8, 4, 8]])

In [64]:
np.sin(arr1)

array([[ 0.14112001,  0.14112001, -0.2794155 ,  0.41211849],
       [ 0.6569866 ,  0.84147098,  0.6569866 ,  0.98935825],
       [-0.2794155 ,  0.98935825, -0.7568025 ,  0.98935825]])

In [65]:
np.cos(arr1)

array([[-0.9899925 , -0.9899925 ,  0.96017029, -0.91113026],
       [ 0.75390225,  0.54030231,  0.75390225, -0.14550003],
       [ 0.96017029, -0.14550003, -0.65364362, -0.14550003]])

In [66]:
np.tanh(arr1)

array([[0.99505475, 0.99505475, 0.99998771, 0.99999997],
       [0.99999834, 0.76159416, 0.99999834, 0.99999977],
       [0.99998771, 0.99999977, 0.9993293 , 0.99999977]])

In [67]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.77815125, 0.95424251],
       [0.84509804, 0.        , 0.84509804, 0.90308999],
       [0.77815125, 0.90308999, 0.60205999, 0.90308999]])

In [68]:
np.exp(arr1)

array([[2.00855369e+01, 2.00855369e+01, 4.03428793e+02, 8.10308393e+03],
       [1.09663316e+03, 2.71828183e+00, 1.09663316e+03, 2.98095799e+03],
       [4.03428793e+02, 2.98095799e+03, 5.45981500e+01, 2.98095799e+03]])

In [70]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 2.44948974, 3.        ],
       [2.64575131, 1.        , 2.64575131, 2.82842712],
       [2.44948974, 2.82842712, 2.        , 2.82842712]])

In [72]:
np.power(arr1,2)

array([[ 9,  9, 36, 81],
       [49,  1, 49, 64],
       [36, 64, 16, 64]], dtype=int32)

In [73]:
np.mean(arr1)

5.833333333333333

In [74]:
np.median(arr1)

6.5

In [76]:
np.std(arr1)

2.4094720491334933

In [77]:
np.var(arr1)

5.8055555555555545

In [78]:
np.min(arr1)

1

In [79]:
np.max(arr1)

9

# END