# Sort, Search and Counting Functions.

In [1]:
import numpy as np

In [2]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [3]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

searchsorted() ---> tells where I can put 34 in the array.

In [5]:
np.searchsorted(arr,34)

12

In [6]:
arr1 = np.array([0,345,454,0,0,0,0])

In [7]:
np.count_nonzero(arr1)

2

In [8]:
np.where(arr>6)   # On which index element is greater than 6

(array([5, 8], dtype=int64),)

In [14]:
np.extract(arr>6,arr)  # Returns array having element greater than 6

array([ 72, 455])

### Byte Swapping

In [16]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [17]:
arr.byteswap()

array([  67108864,   50331648,   67108864,   83886080,  100663296,
       1207959552,   50331648,   50331648, -956235776,   83886080,
        100663296,  100663296])

### Copies and Views

In [18]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [21]:
a = np.copy(arr)    #  Deep copy

In [22]:
a[0] = 10000

In [23]:
a

array([10000,     3,     4,     5,     6,    72,     3,     3,   455,
           5,     6,     6])

In [24]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
b = arr.view()    #shallow copy

In [25]:
b[0] = 1000   # In this arr will also be changed.

In [26]:
b

array([1000,    3,    4,    5,    6,   72,    3,    3,  455,    5,    6,
          6])

In [27]:
arr

array([1000,    3,    4,    5,    6,   72,    3,    3,  455,    5,    6,
          6])

### Matrix Library

In [29]:
import numpy.matlib as nm

In [30]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [31]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Linear Algebra

In [34]:
arr1 = np.random.randint([[2,3], [4,5]])
arr2 = np.random.randint([[5,3], [2,5]])

In [35]:
np.dot(arr1,arr2)  # same as matrix multiplication.

array([[0, 0],
       [4, 2]])

In [36]:
arr1@arr2

array([[0, 0],
       [4, 2]])

# END