# Logistic Regression

### Importing Datasets 

In [54]:
from sklearn.datasets import load_iris
dataset = load_iris()

In [55]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [56]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

### Importing Libraries

In [57]:
import pandas as pd
import numpy as np  



In [58]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df['target'] = dataset.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

#### Transforming iris dataset for binary classification.

In [60]:
df_copy = df[df['target']!=2]
df_copy.shape       


(100, 5)

### Splitting into dependent and independent features

In [64]:
X = df_copy.iloc[:,:-1]
y = df_copy.iloc[:,-1]

### Train-test split

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.20, random_state=42)

In [66]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

classifier.fit(X_train,y_train)

LogisticRegression()

In [67]:
y_pred = classifier.predict(X_test)

In [72]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1])

In [71]:
y_prob = classifier.predict_proba(X_test)

In [73]:
y_prob

array([[0.00144451, 0.99855549],
       [0.01745661, 0.98254339],
       [0.00359664, 0.99640336],
       [0.96427472, 0.03572528],
       [0.93476204, 0.06523796],
       [0.96670676, 0.03329324],
       [0.99197567, 0.00802433],
       [0.03414716, 0.96585284],
       [0.97022597, 0.02977403],
       [0.97501069, 0.02498931],
       [0.94876941, 0.05123059],
       [0.95432911, 0.04567089],
       [0.00502877, 0.99497123],
       [0.98309763, 0.01690237],
       [0.01045624, 0.98954376],
       [0.97788605, 0.02211395],
       [0.00251305, 0.99748695],
       [0.00154296, 0.99845704],
       [0.96995374, 0.03004626],
       [0.95518866, 0.04481134],
       [0.00835685, 0.99164315],
       [0.02378303, 0.97621697],
       [0.95343728, 0.04656272],
       [0.98084327, 0.01915673],
       [0.02881772, 0.97118228],
       [0.97696692, 0.02303308],
       [0.97878312, 0.02121688],
       [0.01706457, 0.98293543],
       [0.96440543, 0.03559457],
       [0.0018048 , 0.9981952 ],
       [0.

### Confusion matric, accuracy score and classifier report

In [70]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred,y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



## HyperParameter Tuning

### GridSearchCV

In [77]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [78]:
parameters = {
    'penalty' : ('l1','l2','elasticnet',None),
    'C': [1,10,20]
}

In [79]:
clf = GridSearchCV(classifier, param_grid=parameters, cv=5)

# Splitting the traning set into validation set
clf.fit(X_train,y_train)
clf.best_params_


{'C': 1, 'penalty': 'l2'}

In [80]:
# Tuning the model
classifier = LogisticRegression(C=1, penalty='l2')
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [83]:
y_pred2 = classifier.predict(X_test)
# Checking the accuracy

print(confusion_matrix(y_pred2, y_test))
print(accuracy_score(y_pred2,y_test))
print(classification_report(y_pred2,y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



### RandomizedSearchCV

In [85]:
from sklearn.model_selection import RandomizedSearchCV
rlf = RandomizedSearchCV(LogisticRegression(), param_distributions=parameters, n_iter=10, cv=5)

rlf.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [87]:
rlf.best_params_

{'penalty': None, 'C': 1}

In [88]:
classifier2 = LogisticRegression(penalty=None, C=1)

In [89]:
classifier2.fit(X_train,y_train)


LogisticRegression(C=1, penalty=None)

In [90]:
y_pred3 = classifier2.predict(X_test)

In [91]:
print(confusion_matrix(y_pred3,y_test))
print(accuracy_score(y_pred3,y_test))
print(classification_report(y_pred3,y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



# END